version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/gatsby-michal-domarus-personal"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
        
